=== Description des interfaces (PAN1 / PAN2)

Pour le PAN1, il faut identifier et décrire sommairement toutes les
interfaces entre modules.

Pour le PAN2, il faut une description complète des interfaces.

Il faut ici une description textuelle de chaque interface, c'est-à-dire chaque
échange entre deux blocs.
Si c’est une interface entre deux blocs informatiques, c’est une interface
Java.
S’il y a des échanges de données complexes, il faut en décrire le format avec
précision.
Si c’est une interface entre deux blocs électroniques, c’est une description
des signaux électroniques ou protocoles utilisés.

==== Interface Utilisateurs---SiteWeb

Cette interface se charge de fournir à l'utilisateur le service web. Dans un sens, l'utilisateur se connecte au travers d'une page web. Dans un autre il reçoit le résultat de la requête d'association par IA (Image-->Son), ce résultat est donc un binaire audio.

==== Interface SiteWeb---BdD

Cette interface se charge de stocker en base de données, les références vers les images choisies par l'utilisateur, dans le cadre de l'évalutation de précision du modèle.


==== Interface SiteWeb---Serveur

Cette interface se charge de l'échanges des données entre le site web (Interface machine de l'utilisateur), et le serveur. Typiquement les données qui vont y transiter seront du type binaire ou stream pour des images d'évaluation du modèle (afin de les stocker localement sur le serveur).

==== Interface Serveur---ServiceGenerationMusique

cette interface se charge de soumettre d'une part, une requête vers l'api du service, avec en paramètres les paramètres des genérations requis par l'API, qui sont eux ajustés par le modèle en fonction de l'image transmise par l'utilisateur. D'autre part, cette interface permet de communiquer au serveur, le binaire de la musique généré. Le format du retour n'est pas encore défini, car nous hésitons entre plusieurs services disponibles sur le net.

==== Interface Serveur---BdD

Cette interface permet de mettre à dispotion à l'IA, un jeu d'entraînement basé sur des images.
